name       : ispell
version    : 3.4.00
release    : 1
source     :
    - http://fmg-www.cs.ucla.edu/geoff/tars/ispell-3.4.00.tar.gz : 5dc42e458635f218032d3ae929528e5587b1e7247564f0e9f9d77d5ccab7aec2
license    : BSD-3-Clause
component  : spelling
summary    : An interactive spell-checking program for Unix
description: |
    An interactive spell-checking program for Unix
build      : |
    install -d -m 00755 /usr/bin
    sed -i -e 's/#undef USG/#define USG/' \
        -e 's|/usr/local|/usr|' \
        -e 's|/lib|/lib/ispell|' local.h.linux
    cp local.h.linux local.h
    %make -j1
install    : |
    %make_install
