name       : ispell
version    : 3.4.04
release    : 4
source     :
    - https://www.cs.hmc.edu/~geoff/tars/ispell-3.4.04.tar.gz : 87bcd6f0521d85a0a3a7834215956d74ebc493144cc7c791f87be6872ccfe13e
license    : BSD-3-Clause
component  : spelling
summary    : An interactive spell-checking program for Unix
description: |
    An interactive spell-checking program for Unix
build      : |
    install -d -m 00755 $installdir/usr/bin
    sed -i -e 's/#undef USG/#define USG/' \
        -e 's|/usr/local|/usr|' \
        -e 's|/lib|/lib/ispell|' local.h.linux
    cp local.h.linux local.h
    %make -j1
install    : |
    %make_install -j1
    # Fix man directories
    install -D -d -m 00755 $installdir/usr/share
    mv $installdir/usr/man $installdir/usr/share/.
    unlink $installdir/usr/lib/ispell/english.hash
    ln -s americanmed.hash $installdir/usr/lib/ispell/english.hash
