name       : ispell
version    : 3.4.05
release    : 6
source     :
    - https://www.cs.hmc.edu/~geoff/tars/ispell-3.4.05.tar.gz : cf0c6dede3fd25fada4375d86acafe583cb96d8fe546de746a92ebb6df895602
homepage   : https://www.cs.hmc.edu/~geoff/ispell.html
license    : BSD-3-Clause
component  : office.spelling
summary    : An interactive spell-checking program for Unix
description: |
    International Ispell is an interactive spell-checking program for Unix which supports a large number of European languages. An emacs interface is available as well as the standard command-line mode.
build      : |
    install -dm00755 $installdir/usr/bin
    sed -i -e 's/#undef USG/#define USG/' \
        -e 's|/usr/local|/usr|' \
        -e 's|/lib|/lib/ispell|' local.h.linux
    cp local.h.linux local.h
    %make -j1
install    : |
    %make_install -j1
    # Fix man directories
    install -D -d -m 00755 $installdir/usr/share
    mv $installdir/usr/man $installdir/usr/share/.
    unlink $installdir/usr/lib/ispell/english.hash
    ln -s americanmed.hash $installdir/usr/lib/ispell/english.hash
